"""HIPAA fax cover sheet generation.

ADR-003 §6: generates attorney/firm-branded cover sheet PDF for
record requests. No TRACE branding. Opaque case reference only.
Includes signed HIPAA authorization reference. No client PII in
cover sheet text — only an opaque case reference.

Uses reportlab for real PDF generation.
"""

from __future__ import annotations

from datetime import datetime, timezone
from io import BytesIO

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas


class CoverSheetGenerator:
    """Generate HIPAA-compliant fax cover sheets for medical record requests."""

    def generate(
        self,
        case_ref: str,
        provider_name: str,
        provider_fax: str,
        return_fax: str = "",
        hipaa_auth_ref: str = "",
        record_types: str = "All available medical records and billing statements",
    ) -> BytesIO:
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter
        today = datetime.now(timezone.utc).strftime("%B %d, %Y")

        # Header
        c.setFont("Helvetica-Bold", 18)
        c.drawString(inch, height - inch, "MEDICAL RECORDS REQUEST")
        c.setFont("Helvetica", 10)
        c.drawString(inch, height - inch - 20, f"Date: {today}")
        c.line(inch, height - inch - 28, width - inch, height - inch - 28)

        # Sender info
        c.setFont("Helvetica-Bold", 12)
        c.drawString(inch, height - inch - 50, "SENDING ATTORNEY / FIRM")
        c.setFont("Helvetica", 10)
        c.drawString(inch, height - inch - 65, f"Return Fax: {return_fax or 'N/A'}")

        # Provider info
        c.setFont("Helvetica-Bold", 12)
        c.drawString(inch, height - inch - 95, "TO (PROVIDER)")
        c.setFont("Helvetica", 10)
        c.drawString(inch, height - inch - 110, f"Provider: {provider_name}")
        c.drawString(inch, height - inch - 125, f"Fax: {provider_fax}")

        # Case reference (opaque only — no client name)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(inch, height - inch - 155, "CASE REFERENCE")
        c.setFont("Helvetica", 10)
        c.drawString(inch, height - inch - 170, f"Reference: {case_ref}")
        c.drawString(inch, height - inch - 185, f"HIPAA Authorization: {hipaa_auth_ref or 'Signed — on file'}")

        # Records requested
        c.setFont("Helvetica-Bold", 12)
        c.drawString(inch, height - inch - 215, "RECORDS REQUESTED")
        c.setFont("Helvetica", 10)
        c.drawString(inch, height - inch - 230, record_types[:120])

        # HIPAA notice
        c.setFont("Helvetica-Oblique", 8)
        c.drawString(inch, height - inch - 270,
            "This fax transmission contains or may contain information protected by HIPAA and state law.")
        c.drawString(inch, height - inch - 282,
            "It is intended only for the named recipient. If you received this in error, please")
        c.drawString(inch, height - inch - 294,
            "notify the sender immediately and destroy the document. Unauthorized review or")
        c.drawString(inch, height - inch - 306,
            "distribution is prohibited by law.")

        # Footer
        c.setFont("Helvetica", 7)
        c.drawString(inch, 30, "Generated by TrueVow TRACE — Treatment Record Acquisition and Chronology Engine")

        c.save()
        buffer.seek(0)
        return buffer
