"""HIPAA fax cover-sheet PDF generator.

Produces a one-page PDF with the case reference (opaque token, NOT client name),
provider details, requested record types, and the HIPAA-authorization reference
number. The signed authorization (which DOES contain PII) is attached to the FAX
as a separate document — never rendered onto the cover sheet where it could be
visible in non-HIPAA-compliant logging.

Uses reportlab (pure Python, no system font deps). Not compilable — the
authorization reference links to securely stored signed documents.
"""

from __future__ import annotations

import io
import uuid
from datetime import date

from reportlab.lib.pagesizes import LETTER  # type: ignore[import-untyped]
from reportlab.lib.units import inch  # type: ignore[import-untyped]
from reportlab.pdfgen import canvas  # type: ignore[import-untyped]

_LEFT = inch
_TOP = LETTER[1] - inch


class CoverSheetGenerator:
    """Generates a single-page fax cover sheet PDF."""

    def __init__(self, disclaimer: str | None = None) -> None:
        self._disclaimer = disclaimer or (
            "HIPAA-CONFIDENTIAL: This transmission contains protected health "
            "information for the authorized recipient only. Mis-delivered copies "
            "must be destroyed without reading and the sender notified immediately."
        )

    def generate(
        self,
        case_ref: uuid.UUID,
        provider_name: str,
        provider_fax: str,
        return_fax: str,
        hipaa_auth_ref: str,
        record_types: str = "All available medical records",
    ) -> io.BytesIO:
        buf = io.BytesIO()
        c = canvas.Canvas(buf, pagesize=LETTER)
        y = _TOP

        c.setFont("Helvetica-Bold", 14)
        c.drawString(_LEFT, y, "TrueVow TRACE — Medical Records Request")
        y -= 22

        c.setFont("Helvetica", 10)
        c.drawString(_LEFT, y, f"Date: {date.today().isoformat()}")
        y -= 14
        c.drawString(_LEFT, y, f"Case Reference: {case_ref}")
        y -= 14
        c.drawString(_LEFT, y, f"HIPAA Authorization Reference: {hipaa_auth_ref}")
        y -= 28

        c.setFont("Helvetica-Bold", 11)
        c.drawString(_LEFT, y, "To (Provider):")
        c.setFont("Helvetica", 10)
        y -= 14
        c.drawString(_LEFT, y, f"  Name: {provider_name}")
        y -= 14
        c.drawString(_LEFT, y, f"  Fax:  {provider_fax}")
        y -= 20

        c.setFont("Helvetica-Bold", 11)
        c.drawString(_LEFT, y, "Requested Record Types:")
        c.setFont("Helvetica", 10)
        y -= 14
        for line in record_types.split(", "):
            c.drawString(_LEFT + 0.25 * inch, y, f"• {line}")
            y -= 12
        y -= 8

        c.setFont("Helvetica-Bold", 11)
        c.drawString(_LEFT, y, f"Return Fax: {return_fax}")
        y -= 20

        c.setFont("Helvetica", 8)
        c.drawString(_LEFT, y, self._disclaimer)
        y -= 10
        c.drawString(
            _LEFT, y, "Signed HIPAA authorization attached. Do not separate cover sheet from authorization."
        )
        y -= 10
        c.drawString(
            _LEFT, y, f"Generated by TrueVow TRACE. Contact support@truevow.law. Ref: {case_ref}"
        )

        c.showPage()
        c.save()
        buf.seek(0)
        return buf
