"""Chronology export — PDF with disclaimer, JSON with schema.

ADR-004 §6: export blocked until demand-ready. Disclaimer on every page.
Two formats: PDF (with footer disclaimer) and JSON (structured for CMS import).
"""

from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone
from io import BytesIO

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

EXPORT_DISCLAIMER = (
    "ATTORNEY WORK PRODUCT — PRIVILEGED AND CONFIDENTIAL\n"
    "This chronology was generated by TRACE and reviewed by the "
    "attorney of record. It organizes factual records for attorney "
    "review and does not constitute medical advice, clinical "
    "interpretation, causation opinion, injury severity assessment, "
    "or case valuation. The attorney is responsible for all legal "
    "judgments made in reliance on this document."
)


class ChronologyExporter:
    def export_pdf(
        self,
        matter_reference: str,
        incident_date: str,
        sol_estimate: str,
        entries: list[dict],
        attorney_name: str = "",
        attorney_bar: str = "",
    ) -> BytesIO:
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter
        today = datetime.now(timezone.utc).strftime("%B %d, %Y")

        # Cover page
        c.setFont("Helvetica-Bold", 16)
        c.drawString(inch, height - inch, "CHRONOLOGY")
        c.setFont("Helvetica", 10)
        c.drawString(inch, height - inch - 20, f"Matter: {matter_reference}")
        c.drawString(inch, height - inch - 35, f"Incident Date: {incident_date}")
        c.drawString(inch, height - inch - 50, f"SOL Estimate: {sol_estimate}")
        c.drawString(inch, height - inch - 65, f"Exported: {today}")
        if attorney_name:
            c.drawString(inch, height - inch - 80, f"Attorney: {attorney_name}")

        # Full disclaimer on cover page
        y = height - inch - 110
        c.setFont("Helvetica-Bold", 10)
        c.drawString(inch, y, "DISCLAIMER")
        c.setFont("Helvetica", 8)
        y -= 14
        for line in EXPORT_DISCLAIMER.split("\n"):
            c.drawString(inch, y, line)
            y -= 11

        # Entries
        y = height - inch - 220
        for entry in entries:
            if y < inch + 40:
                c.showPage()
                y = height - inch
                # Footer on every page
                c.setFont("Helvetica", 7)
                c.drawString(inch, 30, "ATTORNEY WORK PRODUCT — PRIVILEGED AND CONFIDENTIAL — Page continues")
            c.setFont("Helvetica-Bold", 9)
            c.drawString(inch, y, f"{entry.get('event_date', '')} — {entry.get('event_type', '')}")
            c.setFont("Helvetica", 8)
            y -= 14
            desc = entry.get("clinical_description", "")[:150]
            c.drawString(inch, y, desc)
            y -= 14
            c.drawString(inch, y, f"Source: {entry.get('source_document_id', '')} p.{entry.get('source_page_number', '')}")
            y -= 20

        # Final page footer
        c.setFont("Helvetica", 7)
        c.drawString(inch, 30, EXPORT_DISCLAIMER.split("\n")[0])

        c.save()
        buffer.seek(0)
        return buffer

    def export_json(
        self,
        matter_reference: str,
        incident_date: str,
        sol_estimate: str,
        sol_table_version: str,
        sol_confirmed: bool,
        entries: list[dict],
        flags_summary: dict | None = None,
    ) -> str:
        return json.dumps(
            {
                "trace_export_version": "1.0",
                "exported_at": datetime.now(timezone.utc).isoformat(),
                "matter_reference": matter_reference,
                "incident_date": incident_date,
                "sol_estimate": sol_estimate,
                "sol_table_version": sol_table_version,
                "sol_attorney_confirmed": sol_confirmed,
                "disclaimer": EXPORT_DISCLAIMER,
                "chronology": entries,
                "flags_summary": flags_summary or {},
            },
            indent=2,
            default=str,
        )
