"""Chronology export — PDF with disclaimer, JSON with schema.

ADR-004 §6: export blocked until demand-ready. Disclaimer on every page.
Two formats: PDF (with footer disclaimer) and JSON (structured for CMS import).

Phase 2A: export includes full source provenance per fact — source document,
page, extraction method, confidence, review status, and contradictions.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from io import BytesIO

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

EXPORT_DISCLAIMER = (
    "ATTORNEY WORK PRODUCT — PRIVILEGED AND CONFIDENTIAL\n"
    "This chronology was generated by TRACE and reviewed by the "
    "attorney of record. It organizes factual records for attorney "
    "review and does not constitute medical advice, clinical "
    "interpretation, causation opinion, injury severity assessment, "
    "or case valuation. The attorney is responsible for all legal "
    "judgments made in reliance on this document."
)


class ChronologyExporter:
    def export_pdf(
        self,
        matter_reference: str,
        incident_date: str,
        sol_estimate: str,
        entries: list[dict],
        attorney_name: str = "",
        attorney_bar: str = "",
    ) -> BytesIO:
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter
        today = datetime.now(timezone.utc).strftime("%B %d, %Y")

        c.setFont("Helvetica-Bold", 16)
        c.drawString(inch, height - inch, "CHRONOLOGY")
        c.setFont("Helvetica", 10)
        c.drawString(inch, height - inch - 20, f"Matter: {matter_reference}")
        c.drawString(inch, height - inch - 35, f"Incident Date: {incident_date}")
        c.drawString(inch, height - inch - 50, f"SOL Estimate: {sol_estimate}")
        c.drawString(inch, height - inch - 65, f"Exported: {today}")
        if attorney_name:
            c.drawString(inch, height - inch - 80, f"Attorney: {attorney_name}")

        y = height - inch - 110
        c.setFont("Helvetica-Bold", 10)
        c.drawString(inch, y, "DISCLAIMER")
        c.setFont("Helvetica", 8)
        y -= 14
        for line in EXPORT_DISCLAIMER.split("\n"):
            c.drawString(inch, y, line)
            y -= 11

        y = height - inch - 220
        for entry in entries:
            if y < inch + 60:
                c.showPage()
                y = height - inch
                c.setFont("Helvetica", 7)
                c.drawString(inch, 30, "ATTORNEY WORK PRODUCT — PRIVILEGED AND CONFIDENTIAL — Page continues")
            c.setFont("Helvetica-Bold", 9)
            event_date = entry.get("event_date", "")
            event_type = entry.get("event_type", entry.get("fact_type", ""))
            c.drawString(inch, y, f"{event_date} — {event_type}")
            c.setFont("Helvetica", 8)
            y -= 14
            desc = entry.get("clinical_description", entry.get("fact_text", ""))[:150]
            c.drawString(inch, y, desc)
            y -= 14
            src_id = entry.get("source_document_id", "N/A")
            src_page = entry.get("source_page_number", "?")
            src_method = entry.get("extraction_method", "")
            src_conf = entry.get("extraction_confidence", "")
            provenance = f"Source: {src_id} p.{src_page}"
            if src_method:
                provenance += f" | Extracted: {src_method}"
                if src_conf:
                    provenance += f" ({src_conf})"
            c.setFont("Helvetica", 7)
            c.drawString(inch, y, provenance)
            review = entry.get("review_status", "")
            if review and review != "UNREVIEWED":
                c.drawString(inch + 300, y, f"[{review}]")
            if entry.get("is_contradicted"):
                c.drawString(inch + 350, y, "[CONTRADICTED]")
            y -= 16

        c.setFont("Helvetica", 7)
        c.drawString(inch, 30, EXPORT_DISCLAIMER.split("\n")[0])

        c.save()
        buffer.seek(0)
        return buffer

    def export_json(
        self,
        matter_reference: str,
        incident_date: str,
        sol_estimate: str,
        sol_table_version: str,
        sol_confirmed: bool,
        entries: list[dict],
        flags_summary: dict | None = None,
        contradictions: list[dict] | None = None,
        missing_evidence: list[dict] | None = None,
    ) -> str:
        payload = {
            "trace_export_version": "2.0",
            "exported_at": datetime.now(timezone.utc).isoformat(),
            "matter_reference": matter_reference,
            "incident_date": incident_date,
            "sol_estimate": sol_estimate,
            "sol_table_version": sol_table_version,
            "sol_attorney_confirmed": sol_confirmed,
            "disclaimer": EXPORT_DISCLAIMER,
            "chronology": entries,
            "flags_summary": flags_summary or {},
        }
        if contradictions:
            payload["contradictions"] = contradictions
        if missing_evidence:
            payload["missing_evidence"] = missing_evidence
        return json.dumps(payload, indent=2, default=str)
